### ISSUE TITLE
Auto Prefix Container Item Field with "Actor." When Adding Actor UUID to Container

### ISSUE THREAD

**Issue by Rabulias** [krbz999/backpack-manager#13]
The height of laziness, I know, but copying the actor UUID does not include the **Actor.** prefix by default, so can you make your field on the container item automatically prefix the value with **Actor.**?

Even fancier, make it conditional: if the entered string does not begin with **Actor:**, add that string at the start.

Thanks!

**Comment by krbz999** [comment]
Pro tip: If you right-click, you copy the UUID instead of the ID.

**Comment by Rabulias** [comment]
Ah! Thanks for that!
