### ISSUE TITLE
Feature Request: Put in and pull out Coins/Money/Gold etc from the Container Actor

### ISSUE THREAD

**Issue by SirAron111** [krbz999/backpack-manager#15]
Basically, as the title states, I was hoping there was a way to add a coin section to the UI, so my groups can store their money in the container as well. To act as a group party storage for coins.

Not sure how it would work with the weight since you can't assign coins a weight but in dnd for example every 50 coins is 1 around pound if that helps. Or maybe an option to display the actor's actual carry capacity and let the actor handle the calculation by just cranking up the str score to make it fit.

Would really appreciate it if coins could work with this module.

**Comment by krbz999** [comment]
> Basically, as the title states, I was hoping there was a way to add a coin section to the UI, so my groups can store their money in the container as well. To act as a group party storage for coins.

How do you imagine this would look in the UI?

> Not sure how it would work with the weight since you can't assign coins a weight but in dnd for example every 50 coins is 1 around pound if that helps. Or maybe an option to display the actor's actual carry capacity and let the actor handle the calculation by just cranking up the str score to make it fit.

Currency weight can be enabled in the system settings.

**Comment by SirAron111** [comment]
I mean basically UI wise, if there was a slot for adding and subtracting currency. Like for 5e dnd for example, a small row of slots for adding or subtracting platinum, gold, electrum, silver and copper pics. Or a button that opens a second UI window with these slots to not clutter the main window.
Basically just a function to add and retrieve currency from the actor used as backpack.
