### ISSUE TITLE
Backpack items are not visible, but it is tracking their prices

### ISSUE THREAD

**Issue by Marlight777** [krbz999/backpack-manager#28]
![image](https://github.com/krbz999/backpack-manager/assets/63486169/a29a0662-1315-47a5-a677-0a95797abfb3)

I would love to know that there is a chance to save this :). Items here were set to weightless, but it is still tracking costs which gives me some hope.

What I have already done.

1. Disabled ALL modules except for this one
2. Cloned the backpack and tried to edit the sheet type.

I use this backpack as a group bag of holding, and there have stored of a lot of items in it. It would be shame to lose this.

**Comment by krbz999** [comment]
Wrong module?

**Comment by Marlight777** [comment]
> Wrong module?

![image](https://github.com/krbz999/backpack-manager/assets/63486169/458ab4a9-f99a-418d-8cd2-635c1bff1adb)

**Comment by krbz999** [comment]
None of what you are describing are features of this module.

**Comment by Marlight777** [comment]
If I have posted in the wrong place please excuse my ignorance, but this isn't a module that allows groups to have 1 container they can all share access to?

**Comment by krbz999** [comment]
This module does not delete items and store them in another item as some embedded data that can't be retrieved; it uses actors, which is safer than what module you have been using.

It doesn't change the weight or price of the backpack item that is used as a link between the actors, which is what is telling me that you are using a different module. This module also does not change the backpack's description, which is what I assume I was meant to be seeing given you showed a picture of the container's `Description` tab.

**Comment by Marlight777** [comment]
So no I could have done a better job describing it. It did not change weight or price.

My hope is that because it STILL shows weight that I didn't lose access to all the items that I can no longer see after the last major update.

**Comment by krbz999** [comment]
Well stop looking at the item and look at the actor you were using, if you insist it's this module.

**Comment by Marlight777** [comment]
I have the item set to be accessible by all players, which is why I just going to it. Can you help me navigate a little more troubleshooting that maybe is common but I cannot think of? I know you are probably bombarded by questions daily, so I appreciate your time.

**Comment by krbz999** [comment]
I do not do troubleshooting for other people's modules.
