### ISSUE TITLE
[Feature Request] Compatibility with DND5E Version 3.0

### ISSUE THREAD

**Issue by SirAron111** [krbz999/backpack-manager#30]
Compatibility with DND5E Version 3.0.
I can't seem to use this module anymore after updating.

**Comment by krbz999** [comment]
Why would you?

**Comment by SirAron111** [comment]
Because it's the best way to manage group inventory and accurately track a bag of holding inventory, the parties keep inventory etc while having them all access it. On their own.
It tracked the weight of stuff, it let you store and retrive currencies and items. by every player that had a linked item in their inventory.
...
The way the new backpacks work are not correct they don't track weight of items within, adding and subtracting currency is off. And you can't have all players access the same bag if you got a bag of holding.

**Comment by krbz999** [comment]
I'm afraid with backpacks being a native feature of the system, there is not much reason to keep up development of this module. Native containers in the dnd5e system are able to do much more than this module allowed already, save the user interface of course.

> The way the new backpacks work are not correct they don't track weight of items within, adding and subtracting currency is off. And you can't have all players access the same bag if you got a bag of holding.

They should be doing all of these things, except the latter.

**Comment by p4535992** [comment]
For anyone interested some friends of mine still use this module so i just integrate on my fork if you need to use on Dnd 3.0

https://github.com/p4535992/foundryvtt-transfer-stuff
