### ISSUE TITLE
System Request: SWADE

### ISSUE THREAD

**Issue by brunocalado** [krbz999/backpack-manager#4]
Hi!

Great module!

Can you make it work for SWADE? Tks

**Comment by krbz999** [comment]
Being completely unfamiliar with SWADE, I would need to know the following from someone knowledgeable on the system:

- What are the item types in the system? (The keys, not the labels.)
- Does the system have the concept of `quantity` of items? If so, where is it stored in item data.
- Does the system have a 'container'-type item?
- Which item types cannot or should not be able to be added to a container actor, and which should?
- Does the system have the concept of 'using' an item, and can this be cancelled, preferably in a pre-hook?

If most of these can be answered, I can take a look at it.

**Comment by brunocalado** [comment]
- What are the item types in the system? (The keys, not the labels.)
weapon 
armor
shield
consumable
gear
power
edge
hindrance
skill
ability

- Does the system have the concept of quantity of items? If so, where is it stored in item data.
weapon: quantity
armor: quantity
shield: quantity
consumable: quantity
gear: quantity

- Does the system have a 'container'-type item?
Not yet. But, it's coming.

- Which item types cannot or should not be able to be added to a container actor, and which should?
**Allowed**
weapon 
armor
shield
consumable
gear

**Not Allowed**
power
edge
hindrance
skill
ability

- Does the system have the concept of 'using' an item, and can this be cancelled, preferably in a pre-hook?
Not sure about this, but consumable will be removed if you check this.
![image](https://user-images.githubusercontent.com/4999783/193634474-28c27914-c228-4517-932e-015dc09937d9.png)
