### ISSUE TITLE
Feature Request: Keep track of weight of the bag's content on the bag's owner's sheet

### ISSUE THREAD

**Issue by szefo09** [krbz999/backpack-manager#7]
The module seems to be really useful so far, but I would like to see it properly tracking the character's carrying capacity.
If a container does not have weightless contents check, it's weight, or something that would represent the weight of the items inside  should update to keep track of the weight of everything in it. 
And when the container has Weightless Contents checked, it should return to just the container's weight, ignoring the weight of the items in it.

**Comment by Orionox** [comment]
This SOOOOO much!

**Comment by krbz999** [comment]
> The module seems to be really useful so far, but I would like to see it properly tracking the character's carrying capacity. If a container does not have weightless contents check, it's weight, or something that would represent the weight of the items inside should update to keep track of the weight of everything in it. And when the container has Weightless Contents checked, it should return to just the container's weight, ignoring the weight of the items in it.

I've not come up with an idiot-proof and clean solution for this. If you have any thoughts on how it would be implemented, I won't mind hearing it. `Libwrapper` won't be used.

**Comment by bsleys** [comment]
Here is just my 2 cp on this cause I'd love to see it implemented also.

Add an item that you don't display in your ui that weighs the same as the initial weight, ie 5 lbs for a backpack.  Then when ever your UI changes change the item in the players inventory to the total weight.  If weightless is checked you just skip the update or for safety sake update the item weight in inventory to the base weight you set prior.  Oh and obviously ignore your hidden item when totaling the weight of the bag contents in your UI but include it the the total when bag is updated in the player inventory.

Along these lines I'd also like to see the weight limit of the bag be enforced some way.  Perhaps not allowing the transfer to the bag if it pushed the bag beyond it's limit or turn the background of the bag contents red to show its overstuffed.

Bob

**Comment by Dialectikal** [comment]
Just came here to request this same thing and saw it was already raised. I'll immediately hop over from using the Item Collection module if this is ever implemented.

**Comment by p4535992** [comment]
Add a  integrartion for this on my [Variant Encumbrance+Midi](https://foundryvtt.com/packages/variant-encumbrance-dnd5e) module for anyone want to give a try

**Comment by JayBGB** [comment]
Hey! I wanted to just ask if there is any news with this. I usually used @p4535992 Variant Encumbrance+Midi module, but I got a new computer and I migrated everything to the newer versions when I downloaded Foundry, so I cannot use their module now and the backpacks not tracking their total weight on the owner sheet is a pain for me now, since I was used to it. Thank you beforehand!

**Comment by FurtherV** [comment]
> > The module seems to be really useful so far, but I would like to see it properly tracking the character's carrying capacity. If a container does not have weightless contents check, it's weight, or something that would represent the weight of the items inside should update to keep track of the weight of everything in it. And when the container has Weightless Contents checked, it should return to just the container's weight, ignoring the weight of the items in it.
> 
> I've not come up with an idiot-proof and clean solution for this. If you have any thoughts on how it would be implemented, I won't mind hearing it. `Libwrapper` won't be used.

Actor Update Hook on the backpack actor updating weight of backpack item on the owner actor?
