### ISSUE TITLE
Feature Request: Item Summary

### ISSUE THREAD

**Issue by webmaster94** [krbz999/backpack-manager#9]
Hello. This module works great and I want to commend you for finally adding this long needed functionality. I was using item containers, but it was a bit clunky and frankly it is safer to store the container data on a separate entity, especially for backup purposes. One feature of Item Containers (https://gitlab.com/tposney/itemcollection) that I did appreciate however is its summary feature for the container. Basically the contents of the container are listed as the item description so when you expand the item in TidySheet you get a list of the items currently there. It would be nice if this could be replicated. 

Current:
![image](https://user-images.githubusercontent.com/85364225/198877503-c7eef353-d057-4795-a987-8d7b69a0fbc2.png)

Item Containers Implementation:
![image](https://user-images.githubusercontent.com/85364225/198877565-b0f567e6-31b6-43df-99f8-18e24133a31b.png)

**Comment by krbz999** [comment]
Thank you for enjoying this module, it means a lot, truly.

With container management becoming a core feature of the system as of dnd5e v3, this module will no longer be developed.
